### ISSUE TITLE
Two commits suggested

### ISSUE THREAD

**Issue by aviraxp** [franciscofranco/one_plus_2#1]
Hello, Francisco!

I saw Sultan pushed 2 commits in Jan, 2017,
https://github.com/sultanxda/android_kernel_oneplus_msm8996/commit/2c772344c6ed3a9de5e52384f9455314296db901
https://github.com/sultanxda/android_kernel_oneplus_msm8996/commit/e2fdb3dc4a733dc603b43d64319c06b441627a31

Seems these two patches are fixes for his previous patches about input divers. I think you merged Lord Boeffla's adapted version into your kernel, though credits are not properly kept by him. So these two fixes are missing. For the second patch you can simply pick it, but for the first it seems should be adjusted. I try it here https://github.com/aviraxp/boeffla-kernel-cm-oneplus2/commit/bf606ea27635676d52ff88072eabe74b37d6fbea , though don't know if the logic is correct.

Cheers, 
Wang

**Comment by franciscofranco** [comment]
My apologies, I didn't see this issue since I have email notifs disabled :(
